<?php


function cpnaa_user_form_alter(&$form, &$form_state, $form_id){
    switch($form_id) {
       case 'user_register_form': // formulario de registro
        $form['info_personal'] = array(
            '#type' => 'fieldset',
            '#title' => t('Informacion del usuario'),
            '#weight' => 1,
        );
        $form['info_personal']['nombre'] = cpnaa_user_form_nombre();
        $form['info_personal']['apellido'] = cpnaa_user_form_apellido(); 
		$form['info_personal']['tipo_documento'] = cpnaa_user_form_identificacion();
        $form['info_personal']['documento'] = cpnaa_user_form_documento();
		$form['info_personal']['telefono'] = cpnaa_user_form_telefono();
        $form['info_personal']['direccion'] = cpnaa_user_form_direccion();
        $deptos=cpnaa_tablas_get_select('departamento');
        $form['info_personal']['departamento'] = array(
            '#type' => 'select',
            '#title' => t('Departamento'),
            '#options' => $deptos, 
            '#default_value' => 'Seleccione uno',
            '#ajax' => array(
                'callback' =>'cpnaa_user_depto_callback',
                'wrapper' => 'form_user_ciudad', 
                ),
        );
        $form['info_personal']['ciudad'] = array(
            '#type' => 'select',
            '#title' => t('Ciudad'), 
            '#prefix' => '<div id="form_user_ciudad">', '#suffix' => '</div>',
        );
        $form['#submit'][] = 'cpnaa_user_register_submit';
    }
   
}

function cpnaa_user_depto_callback(&$form, $form_state){
    $ciudad=cpnaa_tablas_get_select('ciudad', $form_state['values']['departamento']);
    $form['info_personal']['ciudad']['#options']=$ciudad;
    $form['info_personal']['ciudad'];
    return $form['info_personal']['ciudad'];
}

function cpnaa_user_register_submit($form, &$form_state)
{
	$data['users_uId']= $form_state['values']['uid'] ;
	$data['tipoDoc_id']=$form_state['values']['tipo_documento'];
	$data['numDocIdentificacion']=$form_state['values']['documento'];
	$data['nombre']=$form_state['values']['nombre'];
	$data['apellido']=$form_state['values']['apellido'];
	$data['ciudad_id']=$form_state['values']['ciudad'];
	$data['telefono']=$form_state['values']['telefono'];
	$data['Direccion']=$form_state['values']['direccion'];
   	$query_create_cart = db_insert('users_ext')
      ->fields($data)
      ->execute();
}


function cpnaa_user_form_identificacion(){
	$form = array();
	$opc=cpnaa_tablas_get_select('tipoidentificacion');
	$form= array(
      '#type' => 'select',
      '#title' => t('Tipo de Identificación'),
      '#options' => $opc,
    );
	return $form;
}


function cpnaa_user_form_nombre(){
	$form = array();
	$form= array(
            '#type' => 'textfield',
            '#title' => t('Nombre'),
        );
	return $form;
}

function cpnaa_user_form_apellido(){
	$form = array();
	$form= array(
            '#type' => 'textfield',
            '#title' => t('Apellido'),
        );
	return $form;
}

function cpnaa_user_form_documento(){
	$form = array();
	$form= array(
            '#type' => 'textfield',
            '#title' => t('Documento'),
        );
	return $form;
}

function cpnaa_user_form_direccion(){
	$form = array();
	$form= array(
            '#type' => 'textfield',
            '#title' => t('Direccion'),
        );
	return $form;
}
function cpnaa_user_form_telefono(){
	$form = array();
	$form= array(
            '#type' => 'textfield',
            '#title' => t('Telefono'),
        );
	return $form;
}

