<?php

global $CPNAA_tablas_names;
/*
 * Variable global con la info de las tablas que se consultan en los formularios
 * 
 * Campos
 *			 	table:Nombre de la tabla en base de datos
 * 				info: Campo para visualización, ejemplo en los selects
 * 				fk: Campo de la llave foranea
 * 				t_fk: Tabla de la llave foranea 
 */
$CPNAA_tablas_names =array(
													'banco'=>array('table'=>'cpnaa_tabla_banco', 'info'=>'nomBanco'),
													'ciudad'=>array('table'=>'cpnaa_tabla_ciudad', 'info'=> 'nomCiudad', 'fk'=>'idDepto', 't_fk'=>'departamento'),
													'departamento'=>array('table'=>'cpnaa_tabla_departamento', 'info'=>'nomDepto'),
												);

include_once 'includes/cpnaa_tablas_upload.inc';
include_once 'includes/cpnaa_tablas_utility.inc';



/*
 *Función menu para el manejo de las tablas 
 */
function cpnaa_tablas_menu() {
    // subida de datos por csv
    $items['admin/config/cpnaa/tablas/upload'] = array(
      'title' => 'Subida de datos a las tablas de cpnaa',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cpnaa_tablas_upload_csv_form'),
      'access arguments' => array('Upload Csv'),
      'file' => '/includes/cpnaa_tablas_upload.inc',
      'type' => MENU_NORMAL_ITEM,
    );
 
    return $items;
  }
  
/**
 * Implements hook_permission().
 */
function cpnaa_tablas_permission() {
	$perm['Upload Csv'] = array(
      'title' => t('Upload CSV'), );	
   
  return $perm;
}
  


